-- V15__chapter_images.sql — per-chapter poster frames for the scrub-bar hover fallback and the
-- in-player scene-selection grid (Task 99 Part C).
--
-- Canonical source: docs/.tasks/99-subtitles-and-chapters.md §Part C.
-- Chapter frames are generated by the off-peak asset worker (medi-assets), exactly like hover
-- previews and trickplay sprites — one small JPEG per chapter on disk, under
-- config_dir/chapter-images/<media_file_id>/<ordinal>.jpg. Two additive columns wire it in:
--
--   * chapters.has_image — 1 once the ordinal's frame has been extracted. `replace_chapters`
--     is delete-then-insert on every re-probe, so this resets to 0 and the worker regenerates
--     the frames next pass (the frames on disk are keyed by media_file_id + ordinal, stable).
--     The client uses it as Jellyfin uses `ImageTag`: show the chapter image on hover / list a
--     scene card only when the chapter actually has a frame.
--   * scan_state.chapter_images_done_at — the asset-worker resume marker, sibling of
--     preview_done_at / trickplay_done_at (V1__init.sql). Stamped once a file's chapter frames
--     are generated — OR immediately for a file with no chapters (nothing to do) — so a
--     chapterless file never lingers in the pending-assets set. NULL on every existing row, so
--     the first off-peak pass after this migration extracts frames for the whole library.
--
-- Additive DDL only (no PRAGMAs — see migrations/README.md); idempotent via refinery version
-- records. `has_image` takes a NOT NULL DEFAULT 0 so existing chapter rows read back as
-- "no image" until the worker fills them.

ALTER TABLE chapters ADD COLUMN has_image INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scan_state ADD COLUMN chapter_images_done_at INTEGER;
